name: Deploy Landing via FTP

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build && npm run export

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.KINGHOST_FTP_HOST }}
          username: ${{ secrets.KINGHOST_FTP_USER }}
          password: ${{ secrets.KINGHOST_FTP_PASSWORD }}
          local-dir: out
          server-dir: ${{ secrets.KINGHOST_FTP_PATH }}
          dry-run: false
