name: Deploy Landing to KingHost

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build && npm run export

      - name: Deploy via Git
        run: |
          git config --global user.email "laisa.rioverde@gmail.com"
          git config --global user.name "Laísa Rioverde"
          git remote add kinghost ${{ secrets.KINGHOST_GIT }}
          git add -A
          git diff-index --quiet HEAD || git commit -m "Deploy automático"
          git push --force kinghost main